### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by lseufer** [jbtibor/SmartThings#4]
I have other Somfy devices connected via my Tahoma. My garage door, smoke detector and a power meter. Is there any easy way to reuse your code to also control/access those ?

Thanks

**Comment by jbtibor** [comment]
Define easy :-) 
Yes it is possible to control all devices what you can control on TaHoma website. Currently I'm adding support for IO roller shutters and IO light sensors. After that I can look at the smoke detector and power meter too, but I'll need some input from you. Remind me in about two weeks ;-)

**Comment by lseufer** [comment]
Sure! Let me know what info you need and I'll provide it to you. I also have a light sensor and IO roller shutters and garage door so if I can help, don't hesitate to ping me.

**Comment by jbtibor** [comment]
If you are ready for adventures you can try what I have. It is a very early test version and I can't test with real IO devices so be ready for errors.
https://drive.google.com/open?id=15KvHTkvuQeHS1y-KwLbdOwI9TNApoOFb

The Smart App has a new name so that can be installed side by side with the other one during testing.
The device handler has to be installed too.

Please try:
1. Log in to Smart App. 
2. Enable debug logging.
3. Select a blind.
4. Try to open and close the blind. Both are expected to run in discrete mode. Other commands are not expected to work.

If open and close are working I'll do the set level next.

**Comment by lseufer** [comment]
OK so I'm getting this, no device is appearing after I am entering my credentials.

 6:38:27 PM: error updateDevices(): Error: groovyx.net.http.HttpResponseException: Unauthorized
 6:38:27 PM: error getAuthorizationHeaderValueCore(): Error: groovyx.net.http.HttpResponseException: Unauthorized
 6:38:27 PM: debug SA 1.2.201800502: [method:GET, uri:https://www.tahomalink.com/enduser-mobile-web/enduserAPI/, path:setup, headers:[Cookie:]]
 6:38:27 PM: debug SA 1.2.201800502: [method:POST, uri:https://www.tahomalink.com/enduser-mobile-web/enduserAPI/, path:login, headers:[Content-Type:application/x-www-form-urlencoded; charset=UTF-8]]
 6:38:27 PM: debug SA 1.2.201800502: getAuthorizationHeaderValueCore() 

My email is luc_at_seufer.blog if you want to communicate  more easily and less publicly.

**Comment by jbtibor** [comment]
Two types of IO blinds with level and illuminance sensor have been added to supported devices.
